version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/API"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    versioning-strategy: auto
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 20